// 'Bridge' to Backend/API. Sends a block request to the API endpoint at
// 'http://localhost:8000/api' and returns one block of rows for AG Grid's
// infinite row model. The grid asks for rows by range (startRow/endRow) and
// the backend does all sorting + filtering against the database.

import type { Tile, Grade } from '../types/Tile';

export interface SortModelItem {
  colId: string;
  sort: 'asc' | 'desc';
}

// Shape the grid sends per block. filterModel is AG Grid's per-column filter
// state, passed through to the backend verbatim.
export interface TileQueryRequest {
  startRow: number;
  endRow: number;
  sortModel: SortModelItem[];
  filterModel: Record<string, unknown>;
  search?: string;
}

export interface TileBlockResponse {
  rows: Tile[];
  lastRow: number; // total matching rows, lets the grid size its scrollbar
}

const BASE_URL = 'http://localhost:8000/api';

// input: a TileQueryRequest describing the block + sort/filter state
// output: TileBlockResponse, wrapped in a Promise
export async function queryTiles(req: TileQueryRequest): Promise<TileBlockResponse> {
  const res = await fetch(`${BASE_URL}/tiles/query`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(req),
  });
  if (!res.ok) throw new Error(`Tiles API error: ${res.status}`);
  return res.json() as Promise<TileBlockResponse>;
}

// Editable fields of a tile (id is autogenerated by the backend).
export interface TileInput {
  type: string;
  wafer: string;
  row: number;
  column: number;
  tileId: string;
  grade: Grade;
}

export async function createTile(input: TileInput): Promise<Tile> {
  const res = await fetch(`${BASE_URL}/tiles`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(input),
  });
  if (!res.ok) throw new Error(`Create tile failed: ${res.status}`);
  return res.json() as Promise<Tile>;
}

export async function updateTile(id: string, input: TileInput): Promise<Tile> {
  const res = await fetch(`${BASE_URL}/tiles/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(input),
  });
  if (!res.ok) throw new Error(`Update tile failed: ${res.status}`);
  return res.json() as Promise<Tile>;
}

export async function deleteTile(id: string): Promise<void> {
  const res = await fetch(`${BASE_URL}/tiles/${id}`, { method: 'DELETE' });
  if (!res.ok) throw new Error(`Delete tile failed: ${res.status}`);
}
